version: "3.8"

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: FDrs81eAMi6x1*_g
    # ports:
    #   - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - shopper
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 15s
      timeout: 10s
      retries: 3

  # Node.js application
  app:
    build: .
    container_name: node-app
    restart: always
    ports:
      - "3001:3001"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      MONGO_URL: mongodb://mongoadmin:FDrs81eAMi6x1*_g@mongo:27017/shopper?authSource=admin
      BASE_URL: http://localhost:3001
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - shopper
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - app-uploads:/app/public/uploads

volumes:
  mongo-data:
  app-uploads:

networks:
  shopper:
